#include <u.h>
#include <libc.h>

/*
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.

The first ten terms would be:

 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

 Let us list the factors of the first seven triangle numbers:

  1: 1
  3: 1,3
  6: 1,2,3,6
 10: 1,2,5,10
 15: 1,3,5,15
 21: 1,3,7,21
 28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
*/

u64int* primes;
u64int limit;

int
isprime(u64int prime)
{
	u64int i;
	u64int start = 2;
	u64int end = prime/start;
	int isprime = 1;

	for(i=start; i<end+1; i++){
		if(prime % i == 0 || prime % (i+2) == 0){
			isprime = 0;
			break;
		}
		end = floor(prime/i);
	}

	return isprime;
}

void
cacheprimes(int x)
{
	primes = (u64int*)malloc(limit*sizeof(u64int));
	u64int found = 0;

	for(u64int i=2;found<500;i++){
		if(isprime(i)){
			primes[found] = i;
			found++;
		}
	}

	print("%lld primes cached\n", limit);
}

u64int*
getprimefactors(u64int triangle)
{
	u64int* factors = (u64int*)malloc(limit*sizeof(u64int));
	u64int divisors = 0; 

	for(u64int i=0;i<limit;i++){
		if(triangle % primes[i]==0){
			factors[divisors] = primes[i];
			divisors++;
		}
	}
	factors[divisors] = 0;

	return factors;
}

u64int
getdivisors(u64int triangle)
{
	// a = 2^x * 3^y
	// divisors (2^0 + ...) * (3^0 + ...)
	u64int divisors = 1;
	u64int *factors = getprimefactors(triangle);

	print("%lld: ", triangle);
	for(u64int i=0;1;i++){
		if(factors[i] !=0){
			print("%lld ", factors[i]);
			//divisors *= pow(factors[i], 0) + pow(factors[i], 1);
		}else{
			break;
		}
	}
	print("\n");

	free(factors);
	return divisors;
}

void
main2()
{
	limit = 500;
	cacheprimes(0);

	u64int triangle = 0;
	u64int divisors = 0;
	for(u64int add=1;divisors<limit+1;add++){
		triangle += add;
		divisors = getdivisors(add);
	}

	print("Triangle number: %lld\n", triangle);

	free(primes);
	exits(0);
}

void
main()
{
	u64int triangle = 0;
	u64int divisors = 0;
	u64int max = 0;

	for(u64int add=1;divisors<500;add++){
		divisors = 0;
		triangle += add;
		max = triangle;
		for(u64int i=1;i<max;i++){
			if(triangle % i == 0){
				divisors += 2;
				max = triangle / i;
			}
		}
	}

	print("Triangle number: %lld\n", triangle);
}
